# Generated by Django 5.2.7 on 2025-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CargoStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('20ft', '20 ft Container'), ('40ft', '40 ft Container'), ('curtainsider', 'Curtainsider'), ('warehouse', 'Warehouse')], max_length=20)),
                ('items_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
